### ISSUE TITLE
Black Line Shows up in Chat

### ISSUE THREAD

**Issue by dannybess** [smilefam/SendBird-iOS#11]
Whenever I type in something to the user, a black line appears.

Screenshot: http://prntscr.com/c0iaxi

**Comment by sf-jin-ku** [comment]
@dannybess is this happening even with our latest sdk v3 sample?

**Comment by dannybess** [comment]
@sf-jin-ku I no longer have this problem - it looks like a bad constraint was set somewhere.

I am now, however, stuck on another problem. Is there anyway to either delete users, or perform a hard reset a SendBird app (without resetting it's App-Id)?

**Comment by sf-jin-ku** [comment]
@dannybess 
You can use our Platform API to deactivate users. There's no reset feature. 
Please contact me and we can try to manually reset your project. 
( jin@sendbird.com  )

**Comment by dannybess** [comment]
@sf-jin-ku I have sent the email. Thanks.
