### ISSUE TITLE
Registering for push notifications always fails

### ISSUE THREAD

**Issue by Arcanfel** [smilefam/SendBird-iOS#12]
```
func application(application: UIApplication, didRegisterForRemoteNotificationsWithDeviceToken deviceToken: NSData) {
    SBDMain.registerPushToken(deviceToken) { (response, error) in
	if let error = error {
		print(error.localizedDescription)
	}

	print(response)
}
```

Always fails with following print output:

> The operation couldn’t be completed. (Connection required. error 800101.)
> nil

**Comment by sf-jin-ku** [comment]
Hi @Arcanfel 
800101 means you need to establish a connection first.
https://docs.sendbird.com/ios#change_log

Please call connectWithUser first then call registerPushToken.
Without connectWithUser, we don't know what user_id we should associate the token with.

Thanks!
Jin

**Comment by Arcanfel** [comment]
Hi @sf-jin-ku! Thanks for the prompt update:)
