### ISSUE TITLE
Small .XIB trap for people dragging the files into their own project

### ISSUE THREAD

**Issue by johngoren** [smilefam/SendBird-iOS#14]
In the Swift project, developers trying to import the Chatting view controller into their personal project might run into a crash that I found the answer to after hours of struggle.

Buried in the Chatting/ViewCell files, one XIBs alone is marked with a custom module setting, "SendBird_iOS," restricting it from being used in any other module. This is "IncomingFileMessageViewCell.xib." If you drag it into your project, your program will crash with an error that can drive you crazy searching for @IBOutlets: "This class is not key-value compliant."

But it turns out the bug has nothing to do with @IBOutlets. If you remove the custom module setting from the XIB, everything will import into your own project much more smoothly.

<img width="265" alt="screen shot 2016-11-07 at 13 57 40" src="https://cloud.githubusercontent.com/assets/748214/20060252/3269760a-a4f2-11e6-9903-7a629366c66e.png">

**Comment by sf-jed-kyung** [comment]
Thanks!

**Comment by sf-jin-ku** [comment]
@johngoren We also applied the same fix to our sample repo as well! Thanks!
