### ISSUE TITLE
One to One 

### ISSUE THREAD

**Issue by SusheelYadavAhex** [smilefam/SendBird-iOS#17]
Hi , 

Thanks for providing this wonderful SDK for Chatting . It's user friendly .  

I have a doubt regarding SendBird SDK . 
Does this SDK Supports one to one chat . I could not found any where in your app. I tried to run your application , when i pressed open channel , it is showing up list of users . By holding on particular user i am not  getting an alert to chat with the respective person . Instead i am getting alert to block user . 

can you please revert back soon  . I am left over with this functionality in my app.

**Comment by sf-jed-kyung** [comment]
Group channel includes 1-on-1 chat. After connection, you can start 1-on-1 chat in Group Channel. Also, I added a new feature to the sample app for starting group channel in open channel. When the profile image is clicked in the open channel, the menus will be shown for it.

**Comment by SusheelYadavAhex** [comment]
Thanks for your reply ,

About my Project Scenario.
I have replaced with my own " Application id " in appdelegate.m , it is
showing up list of DMV offices of particular area .
Now i need to interact with particular DMV offices . lets say suppose i
have xyzdmvoffice ..so lot of members will join in that xyzdmvoffice . So i
picked up random user and i want to chat with him directly . Does this
scenario works on your SDK .

I need bit of clarity in one to one chat .
In open channel i need to have one to one chat ,  is it possible . I have
tried by holding on profile picture in open channel , from below it is
popping  up like an action sheet  producing three values like (user profile
name , block user , cancel). And more over the user profile name is not
highlighted (it is like light grey color , remaining are in dark blue color
).

Note : Currently i am testing in ios simulator .

Please revert back soon .

Thank you
Susheel Yadav

**Comment by sf-jed-kyung** [comment]
I updated the sample app for the feature to start group channel in open channel in v3.0.8. Please try to run the version.

**Comment by SusheelYadavAhex** [comment]
Sure ,
Thanks for your reply .
