### ISSUE TITLE
SBDGroupChannel last message bug

### ISSUE THREAD

**Issue by swiftymarks** [smilefam/SendBird-iOS#18]
Hello this is a snippet code of mine in where variable ch is as class of SBDGroupChannel
```
 let lastMessage = ch.lastMessage
      if let lastMessage = lastMessage{
        if let userLastMessage = lastMessage as? SBDUserMessage{
          cell.lastMessageLabel.text = userLastMessage.message
        }
        if let _ = lastMessage as? SBDFileMessage{
          cell.lastMessageLabel.text = "File Attachment"
        }
      }else{
        cell.lastMessageLabel.text = "No Message yet"
      }
}
```

The problem is the last message only get the last available instance of SBDUserMessage in the chats. If SBDFileMessage was the last message it always return the last available SBDUserMessage instance in the chat so 

```
 if let _ = lastMessage as? SBDFileMessage{
          cell.lastMessageLabel.text = "File Attachment"
        }
```
alwsys failed

**Comment by swiftymarks** [comment]
This bug also appears in the Android SDK

**Comment by sf-jed-kyung** [comment]
I think this is the server-side problem. Please send support@sendbird.com your App ID.

**Comment by sf-jed-kyung** [comment]
We have an option on our dashboard to solve your problem. You can see `Notifications for File Message` option in `SETTINGS` tab on the dashboard for an app that has the problem. If you turn the option on, the file message will be set to the last message of the group channel. Be aware that you cannot turn off it again after turning on.
