### ISSUE TITLE
Api Token Missing Error 

### ISSUE THREAD

**Issue by SusheelYadavAhex** [smilefam/SendBird-iOS#19]
Hi, 
Currently i am using **Sendbird-iOS- SDK  V3   (Obj-C)** with **Xcode** Version 8.2.1 (8C1002)

While I was trying to get list of  "open channels" available in my Sendbird application dashboard,  
I am getting API Token error message. 
`Not valid Api-Token. Api-Token is missing.
`

The alert message  is firing  in OpenChannelListViewController.m , in this method 

```
[self.openChannelListQuery loadNextPageWithCompletionHandler:^(NSArray<SBDOpenChannel *> * _Nullable channels, SBDError * _Nullable error) 
{
}

```

After debugging , i found that it was requesting the "Api-Token" Header in request to the following URI 

> https://api.sendbird.com/v3/open_channels?token=&limit=20 

I have configured Sendbird app id.

How can I append the **Api-Token** header in the request. 

Note : I am testing in IOS - Simulator .

**Comment by andy318** [comment]
I'm encountering the same issue.

**Comment by sf-jed-kyung** [comment]
I think the connection is not opened when the method is invoked. Please check the `connectWithUserId:` method is called and completed.
