### ISSUE TITLE
No Module found : AlamofireImage 

### ISSUE THREAD

**Issue by badrinathvm** [smilefam/SendBird-iOS#20]
<img width="758" alt="screen shot 2017-01-02 at 4 48 13 pm" src="https://cloud.githubusercontent.com/assets/1479179/21598123/71bbbf76-d10b-11e6-9317-a4f6ff083a36.png">

Hello, 

Facing a issue in swift project No Module found AlamofireImage , Can you help in providing pointers in solving it ?

Thanks again.

**Comment by sf-jed-kyung** [comment]
Did you open `SendBird-iOS.xcworkspace` in Xcode?

**Comment by badrinathvm** [comment]
On opening SendBird-iOS.xcworkspace works as expected.. Thanks a ton..

**Comment by badrinathvm** [comment]
Closing the issue
