### ISSUE TITLE
Can't archive the swift project

### ISSUE THREAD

**Issue by binishkaspar** [smilefam/SendBird-iOS#22]
Application works good when running on device and but can't archive. 

`Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1`

Do i need to do anything before archive the project?

**Comment by sf-jed-kyung** [comment]
Thank you for having informed us. The problem is related to Optimization Level for Release. Please change `Swift Compiler - Code Generation > Optimization Level > Release` to `None[-Onone]` in `Build Settings` of `SendBird-iOS` Targets.

**Comment by binishkaspar** [comment]
It worked. Thanks.
