### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by mzrzvi** [smilefam/SendBird-iOS#23]
Every time I send a message in a group channel and try to go back to the group channels the app crashes and gives me the error:

```
fatal error: Index out of range
```

**Comment by sf-jed-kyung** [comment]
Could you tell me the number of the line that makes crash?

**Comment by mzrzvi** [comment]
I added some code so this may not be the exact line but I think it's 220

![image](https://cloud.githubusercontent.com/assets/5845401/26330441/881701c6-3f11-11e7-98b7-1c4c3cf198b8.png)

**Comment by famous90** [comment]
@mzrzvi Sorry to reply late. Have you resolved your issue? If not, plz let me know more crash info. I'll help you ASAP.

**Comment by mzrzvi** [comment]
@famous90 No longer involved in the project! Thank you though
