### ISSUE TITLE
The layout bug

### ISSUE THREAD

**Issue by nickpali** [smilefam/SendBird-iOS#27]
The layout bug fix made 10 days ago doesn't work with iPhone 5s, the messages are still overlapping with iPhone 5s on 10.3.3

**Comment by ohadnav** [comment]
Also happens for iPhone 7

**Comment by sf-jed-kyung** [comment]
Please check out the https://github.com/smilefam/SendBird-iOS/commit/c8a4383b3786d969dcc1eecb9684c0d5c64492ee commit.

Thanks.
