### ISSUE TITLE
Error in xCode 10 with Swift 4.2

### ISSUE THREAD

**Issue by StellarKuldeep** [smilefam/SendBird-iOS#49]
Getting below error in `getHeightOfViewCell` 

**The compiler is unable to type-check this expression in reasonable time; try breaking up the expression into distinct sub-expressions**

How to fix this?

**Comment by andreasorel** [comment]
Hi, what this is saying is that your need to break up the expression. For example you can do this:

`let messageLabelMaxWidthSub1 = self.profileImageLeftMargin.constant + self.profileImageWidth.constant + self.messageContainerLeftMargin.constant + self.messageContainerLeftPadding.constant
        let messageLabelMaxWidthSub2 = self.messageContainerRightPadding.constant + self.messageDateLabelLeftMargin.constant + self.messageDateLabelWidth.constant + self.messageDateLabelRightMargin.constant
        
        let messageLabelMaxWidth = UIScreen.main.bounds.size.width - (messageLabelMaxWidthSub1 + messageLabelMaxWidthSub2)`

**Comment by nejcpintar** [comment]
Someone resolve this, fixing all those errors was time consuming
