### ISSUE TITLE
How to check receiver read the message or not?

### ISSUE THREAD

**Issue by StellarKuldeep** [smilefam/SendBird-iOS#55]
I created 1 channel with 1 to 1 chat and now i want to show the message read status like as WhatsApp.
I review docs but doesn't find anything so i request you to please help me regarding this.

I want to do something like this.
When sender send message and once receiver read the message then sender receive some flag like `IsRead = true/false`.

How can o do this?

Any help will be appreciated.
Thanks in advance.

**Comment by janna-sendbird** [comment]
Hello @StellarKuldeep,

When a user reads a message, the app can call the markAsRead method to denote that he/she has read the message. https://docs.sendbird.com/ios/group_channel_advanced#3_mark_messages_as_read

The app can also retrieve an array of members who have read a message, and you can determine if the receiver has read the message or not.
https://docs.sendbird.com/ios/group_channel_advanced#3_retrieve_members_who_have_read_a_message

**Comment by StellarKuldeep** [comment]
@janna-sendbird , Thanks for your help. I try to get numbers of read members using this 

`let unreadMember = self.groupChannel.getReadMembers(with: message, includeAllMembers: true)`

But the issue is when i send new message to other user and comes to chattingView for 1st time then new message

**Comment by StellarKuldeep** [comment]
@janna-sendbird , Thanks for your help, i have done this. Now you can close this question.

**Comment by janna-sendbird** [comment]
Hi @StellarKuldeep 
Good to hear that you are able to track the unread counts now in your app.
As an alternative to adding the property, you can use the channelDidUpdateReadReceipt(_ sender: SBDGroupChannel) function, and if sender == self.channel, then you can update the read statuses for the messages.
