### ISSUE TITLE
pod install 

### ISSUE THREAD

**Issue by ylaznik** [smilefam/SendBird-iOS#6]
Hey , 

Your pod contains a reference to a local folder on your drive :  Users/jedkyung/git/sendbird-ios-framework .  Even after fixing this you get a bunch of errors in the install . would appreciate some help

**Comment by sf-jed-kyung** [comment]
Sorry. I made a mistake. Please download the latest commit again. Thanks.

**Comment by ylaznik** [comment]
Dont sweat it man,  shit happens .

your pod doesnt connect to target build
still not working

**Comment by ylaznik** [comment]
try this

**Comment by sf-jed-kyung** [comment]
I couldn't figure out the problem. However, I realized SendBird framework(v2.2.0) had some bugs, so I updated the framework v2.2.1. Could you try to build the latest version?

**Comment by ylaznik** [comment]
Sure .

It was a small issue with the pod file .  I sent you a working version of
the podfile that I made .

Im integrating it next week , Ill let you know if I find anything wrong
with it .

Many thanks

**Comment by sf-jed-kyung** [comment]
I can't see your Podfile. Where is it?

**Comment by ylaznik** [comment]
platform :ios, '8.0'
use_frameworks!
pod "SendBirdSDK"
pod "AFNetworking"



target 'SendBird Sample UI' do

end

target 'SendBirdSampleUITests' do

end

target 'SendBirdSampleUIUITests' do

end

**Comment by sf-jed-kyung** [comment]
Try like this:

```
platform :ios, '8.0'
use_frameworks!

target 'SendBird Sample UI' do
  pod "SendBirdSDK"
  pod "AFNetworking"
end

target 'SendBirdSampleUITests' do
  pod "SendBirdSDK"
  pod "AFNetworking"
end

target 'SendBirdSampleUIUITests' do
  pod "SendBirdSDK"
  pod "AFNetworking"
end
```

or remove all of targets:

```
platform :ios, '8.0'
use_frameworks!
pod "SendBirdSDK"
pod "AFNetworking"
```
