### ISSUE TITLE
Media with caption

### ISSUE THREAD

**Issue by shuuja** [smilefam/SendBird-iOS#60]
is there a way to send media (i.e. image , video) with caption in one message?

**Comment by sf-jed-kyung** [comment]
Send a file message with data that has the caption.

If you want to send a file message with an `SBDFileMessageParams`, set the caption in the data of the `SBDFileMessageParams` object:
https://docs.sendbird.com/ref/ios/Classes/SBDBaseMessageParams.html#//api/name/data

If you want to use a method to send a file message, use the method that has a data parameter:
https://docs.sendbird.com/ref/ios/Classes/SBDBaseChannel.html#//api/name/sendFileMessageWithBinaryData:filename:type:size:thumbnailSizes:data:customType:progressHandler:completionHandler:

You can see the caption in the data of the file message:
https://docs.sendbird.com/ref/ios/Classes/SBDBaseMessage.html#//api/name/data
