### ISSUE TITLE
How to i create new a user?

### ISSUE THREAD

**Issue by yothin** [smilefam/SendBird-iOS#7]
In document 
"SendBird requires only UserId and Nickname to login in Client SDK by default"

but 

`Please make sure that you create two users before starting messaging and correctly passing target user id with setTargetUserId.`

Don't have any tutorial create new user before login with SendBird

Thank you

**Comment by sf-jed-kyung** [comment]
SendBird has two ways to create a user. 

* Logging in method in SDK.

You can log in SendBird with unique user id. If there isn’t the user who has the user id in SendBird, the user will be created and logged in. If there is the user who has the id, the user will be reused and logged in.

* Server API

SendBird provides Server API to create a user. Access token can be set by Server API only.
Please refer to https://sendbird.gitbooks.io/sendbird-server-api/content/en/user.html

**Comment by yothin** [comment]
thank you, I'll try this.

**Comment by Ankur008** [comment]
Hey @yothin did you are able to create user?
