### ISSUE TITLE
Syntax errors for iOS 10 in Xcode 8 (Swift 2.3 and Swift 3)

### ISSUE THREAD

**Issue by ericandrewmeadows** [smilefam/SendBird-iOS#8]
Most of the code is broken with the new release of Xcode 8.  There are many syntax changes, such as https://github.com/apple/swift-evolution/blob/master/proposals/0086-drop-foundation-ns.md, the changing of camel case, CGColor -> cgColor, etc.  Please create a Swift 2.3- or Swift 3-compatible branch.

**Comment by sf-jed-kyung** [comment]
Thank you for letting us know. We will create the branch for that as soon as possible.

**Comment by sf-jin-ku** [comment]
@ericandrewmeadows We've been working on new SDK so this support got delayed. Sorry for that. We will take a look at this issue and should be resolved before the official iOS 10 release.

**Comment by BrandonS6265** [comment]
Any word on this?

**Comment by sf-jed-kyung** [comment]
We uploaded the samples to support Swift 2.3 and Swift 3 to `swift-2.3` and `swift-3` branches.
