### ISSUE TITLE
Wrong word wrapping

### ISSUE THREAD

**Issue by hash3r** [smilefam/SendBird-iOS#9]
Why do you need these replaces in string?
```
message = message.stringByReplacingOccurrencesOfString(" ", withString: "\u{00A0}")
message = message.stringByReplacingOccurrencesOfString(" ", withString: "\u{2011}")
```
Do you know that it breaks word wrapping in any containers like UILabel or UITextView?

**Comment by sf-jed-kyung** [comment]
You’re right. Ignore the codes. They aren’t necessary. 👍
